### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by cofob** [nix-community/mineflake#17]

**Comment by IogaMaster** [comment]
SVG
![logo](https://github.com/nix-community/mineflake/assets/67164465/ab5c89f8-112b-4206-ac07-557ad6b4bbde)

PNG
![image140](https://github.com/nix-community/mineflake/assets/67164465/99090c77-a3dc-4ef2-89f5-2bfd1f665f51)

If you use please credit! Other than that idc

**Comment by IogaMaster** [comment]
I might recolor the minecraft block, and can remove rainbow if you want

**Comment by cofob** [comment]
> @cofob
> SVG
> ![logo](https://github.com/nix-community/mineflake/assets/67164465/ab5c89f8-112b-4206-ac07-557ad6b4bbde)
> 
> PNG
> ![image140](https://github.com/nix-community/mineflake/assets/67164465/99090c77-a3dc-4ef2-89f5-2bfd1f665f51)
> 
> If you use please credit! Other than that idc

Thank you so much! It's a great option for the logo, I'll try to embed it soon.

**Comment by IogaMaster** [comment]
Perfect, looking to use this project. 
Source images:
![image](https://github.com/nix-community/mineflake/assets/67164465/2fc995a9-a26a-4b2d-bd25-3f646b46cd0a)
![io mrarm mcpelauncher](https://github.com/nix-community/mineflake/assets/67164465/2e92ead3-946d-41f4-aae3-df8ac0a46054)

**Comment by HannesGitH** [comment]
Something in me eagerly wants to rotate the nix part of the logo, s.t. the two hexagons align :P

**Comment by IogaMaster** [comment]
I tried that, it looked weird.
I dont have the files anymore
