### ISSUE TITLE
(nix)- Source for packages

### ISSUE THREAD

**Issue by TyberiusPrime** [nix-community/mineflake#83]
Hey,
great work with mineflake!.

I'd like to run paper with geyserMC, but apparently I need to upgrade paper to 1.19.4 first.

It's getting read via IPFS from a 'server.zip' file, but I'm unsure where I can find the source to that,
so I can rebuild it with the newer paper?

Or is it just a matter of downloading the old, swapping out the jars? 

Any pointers are appreciated!
Thank you.

**Comment by cofob** [comment]
Hello!

This file is defined here:
https://github.com/nix-community/mineflake/blob/2bfb40a846504251e42fe5fe3e294d2a5d387219/pkgs/servers/shortbin.nix#L4-L7

It is created manually by downloading a new version from [papermc site](https://papermc.io/downloads/paper), running and creating a manifest file, and archiving to zip all the files. We, unfortunately, could not find a way to package and build the java jar files, as the build:

1. Complicated and unique to almost every project. That paper is essentially a collection of patches, you have to build in a special way.
2. When nixpkgs updates dependency hashes change, the build becomes unreproducible. 

If you have solutions to these problems, I would be happy to hear them.

**Comment by TyberiusPrime** [comment]
Thank you for your fast reply!

Sorry, I don't have a better solution than packing the "binary" either.

It's this part I'm unclear about "... manually by downloading a new version from [papermc site](https://papermc.io/downloads/paper), running and creating a manifest file, and archiving to zip all the files.", Specifically what to download and how the manifest is created. Sorry, my Minecraft knowledge is very limited :).

 Maybe we could automate that part, starting with a hash of the Jar?

**Comment by cofob** [comment]
You can read more about packaging in the [documentation](https://mineflake.cofob.dev/packaging/overview/).
It is difficult to automate, because with jar updates the configuration files change as well, it is important to keep them up to date.

**Comment by TyberiusPrime** [comment]
Ok, package.yml.is clear, the paper.jar is clear, but where do all the other jars in the server.zip for paper come from? 
 Sorry for being a bit obtuse.

**Comment by cofob** [comment]
They are created/downloaded by the paper itself at first startup. They are added to the package to speed up startup and allow you to run without the internet.
